version: "3.3"

services:
  api:
    container_name: stone-api
    image: node:12
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    networks:
      - base
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    env_file:
      - .env

networks:
  base:
